name: users_app
description: "A very basic application consumes on JSON Placeholder api"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  flutter_riverpod: 2.4.10
  go_router: 13.2.0
  equatable: 2.0.5
  dio: 5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 3.0.1

flutter:
  uses-material-design: true
